### ISSUE TITLE
Implement automatic testing

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#10]

**Comment by goanpeca** [comment]
@jitseniesen you mean continuous integrations?

I am updating the CI + ciocheck on the different repos, I can do this :-)

**Comment by jitseniesen** [comment]
@goanpeca Yes, I mean continuous integration. It would be great if you could set it up. At the moment, there is only one test, so it's not urgent, but I would like to have it in place before the first release.

**Comment by goanpeca** [comment]
Ok, I will do it on Sunday night, I will take care of it :-)

**Comment by jitseniesen** [comment]
@goanpeca Just in case you did not notice ... I did rename the repository and plugin as suggested in #24 .

**Comment by jitseniesen** [comment]
Re-opening since the tests don't actually run ... :disappointed:

**Comment by jitseniesen** [comment]
Working now :)
