### ISSUE TITLE
Report pytest plugins used while running a test suite

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-unittest#115]
Since #114 will allow to run Spyder test suite inside Spyder itself (great achievement!) I'd like the plugin to report the installed pytest plugins (just like `pytest foo.py` does).

This is sometimes helpful for me, so it'd be nice to have it here too.

**Comment by bilderbuchi** [comment]
Maybe a good idea to capture the whole "intro" output that pytest spits out in the beginning (which contains the plugins loaded). This info will be practical if you have to debug any problems with your test runs.

**Comment by jitseniesen** [comment]
In fact, the whole output is captured and displayed if you click "Show output" in the options menu in the plugin window. This allows you to find out the versions of your pytest plugins. Nevertheless, a more user friendly option is certainly worth having.

**Comment by jitseniesen** [comment]
Fixed by PR #146
