### ISSUE TITLE
Config option to disable abbreviations

### ISSUE THREAD

**Issue by VolkerSiep** [spyder-ide/spyder-unittest#122]
Hi,

in reference to the linked line of code ([datatree.py#L307](https://github.com/spyder-ide/spyder-unittest/blob/56fecf805d4a93c31dc9427e3c7690c07ff72809/spyder_unittest/widgets/datatree.py#L307)):

I find these abbreviations for my case (using standard lib unittest) disadvantageous and hacked it into
`return self.testresults[row].name` without much understanding the code :). Let me suggest to add a configuration option to the "Configure tests" dialog that allows to switch the feature on and off.

BTW: Thanks for the plugin. Good work!

With best regards / Volker

**Comment by jitseniesen** [comment]
Yes, it does depend on naming and other conventions whether these abbreviations are advantaguous, so it's a good suggestion to add a config option for this.

Thanks for your kind words.
