### ISSUE TITLE
KeyError: 'test not found'

### ISSUE THREAD

**Issue by ocroquette** [spyder-ide/spyder-unittest#128]
## Description of your problem

The plugin throws the following exception when running the unit tests:

```
File "C:\Dir\python-3.7.4.amd64\lib\site-packages\spyder_unittest\widgets\unittestgui.py", line 342, in tests_started
    self.testdatamodel.update_testresults(testresults)
  File "C:\Dir\python-3.7.4.amd64\lib\site-packages\spyder_unittest\widgets\datatree.py", line 265, in update_testresults
    raise KeyError('test not found')
KeyError: 'test not found'

Traceback (most recent call last):

  File "C:\Dir\python-3.7.4.amd64\lib\site-packages\spyder_unittest\widgets\unittestgui.py", line 354, in tests_yield_result
    self.testdatamodel.update_testresults(testresults)
  File "C:\Dir\python-3.7.4.amd64\lib\site-packages\spyder_unittest\widgets\datatree.py", line 265, in update_testresults
    raise KeyError('test not found')
KeyError: 'test not found'
```

## What steps will reproduce the problem?

1.  Extract the attached project : [sample-project.zip](https://github.com/spyder-ide/spyder-unittest/files/3733807/sample-project.zip)
2. Create a new project in Spyder and point it to the extracted directory
3. Run the unit tests

## What is the expected output? What do you see instead?

Error dialog comes up with the given Exception. Test results pane is empty.

### Paste traceback/error below (if applicable)

See above

## Key versions and other information:

* Spyder version: 3.3.6
* Version of spyder-unittest plugin: 0.3.1
* Installation method for Spyder and the unittest plugin: pip
* Python version: 3.7.4
* Testing framework used: nose / py.test / unittest: py.test
* Testing framework version: 5.2.0 or 5.2.1, not sure
* Operating system: Windows

**Comment by ocroquette** [comment]
I found a fix. If I delete the file ```__init__.py``` from the ```tests``` directory, the error doesn't occur anymore. I don't really understand why, but at least I am not blocked anymore. Still, the root cause should be fixed, or at least the error message should be improved.

**Comment by jitseniesen** [comment]
I think I reproduced this. I do not quite understand what is going on, I think pytest is recording the test names differently in the discovery phase. I have an idea on how to work around.

**Comment by ocroquette** [comment]
Thank you for the feedback. By the way, does the plugin work with Spyder 4 ? I installed both from PyPi recently, and I could not find the usual menu entries like "Run unit tests".

**Comment by jitseniesen** [comment]
> does the plugin work with Spyder 4 ?

No. We are working on it; hopefully we can release a new version of the plugin which fixes this issue and is also compatible with Spyder 4 in a week or so.

**Comment by ocroquette** [comment]
OK, thank you for the info and your work.

**Comment by ocroquette** [comment]
Thanks! I can also confirm that the current "master" version works with Spyder 4 now.

**Comment by jitseniesen** [comment]
That is good to know. We are in the process of releasing the current "master" version officially.
