### ISSUE TITLE
spyder - Unit Testing tab does not appear - MAC

### ISSUE THREAD

**Issue by gabrielburcea** [spyder-ide/spyder-unittest#137]
## Unit Testing tab does not appear - MAC

I am working with spyder - python. I want to test my codes. I have followed the pip install spyder-unittest and pip install pytest. I have restarted the kernel and restarted my MAC as well. Yet, Unit Testing tab does not appear. Even when I drop down Run cannot find the Run Unit test. Does someone know how to do this?

**Comment by jitseniesen** [comment]
We recommend the use of `conda` instead of `pip`, because `pip` has fewer checks for inconsistencies, which makes it hard to find installation issues such as you are experiencing. In fact, we do not have enough people to provide help with `pip` installations.

Please fill out the requested version information instead of deleting the questions. Run spyder with the command `spyder --debug-info verbose` and look for errors.

**Comment by gabrielburcea** [comment]
I have used `conda` instead of `pip`. Yet I got so many conflicts like these:
Package python-language-server conflicts for:
spyder=4.0.1 -> python-language-server[version='>=0.31.2,<0.32.0']
spyder-notebook -> spyder[version='>=3.2'] -> python-language-server[version='>=0.31.2,<0.32.0']

Package wurlitzer conflicts for:
spyder=4.0.1 -> spyder-kernels[version='>=1.8.1,<2.0.0'] -> wurlitzer[version='>=1.0.3']
spyder-kernels -> wurlitzer[version='>=1.0.3']
anaconda==2019.10 -> wurlitzer==1.0.3[build='py27_0|py36_0|py37_0']
anaconda==2019.10 -> spyder-kernels==0.5.2=py36_0 -> wurlitzer

```
Package matplotlib-base conflicts for:
nltk -> matplotlib -> matplotlib-base[version='3.1.2|3.1.2|3.1.2|3.1.3',build='py37h9aa3819_1|py36h9aa3819_0|py37h9aa3819_0|py38h9aa3819_0|py38h9aa3819_1|py36h9aa3819_1']
seaborn -> matplotlib[version='>=2.1.2'] -> matplotlib-base[version='3.1.2|3.1.2|3.1.2|3.1.3',build='py37h9aa3819_1|py36h9aa3819_0|py37h9aa3819_0|py38h9aa3819_0|py38h9aa3819_1|py36h9aa3819_1']
bokeh -> matplotlib -> matplotlib-base[version='3.1.2|3.1.2|3.1.2|3.1.3',build='py37h9aa3819_1|py36h9aa3819_0|py37h9aa3819_0|py38h9aa3819_0|py38h9aa3819_1|py36h9aa3819_1']
matplotlib -> matplotlib-base[version='3.1.2|3.1.2|3.1.2|3.1.3',build='py37h9aa3819_1|py36h9aa3819_0|py37h9aa3819_0|py38h9aa3819_0|py38h9aa3819_1|py36h9aa3819_1']
scikit-image -> matplotlib[version='>=2.0.0'] -> matplotlib-base[version='3.1.2|3.1.2|3.1.2|3.1.3',build='py37h9aa3819_1|py36h9aa3819_0|py37h9aa3819_0|py38h9aa3819_0|py38h9aa3819_1|py36h9aa3819_1']
```

**Comment by gabrielburcea** [comment]
tried the `conda` yet I got lots of conflicts, I will put just first three lines as there are way to many conflicts:

````
Package zeromq conflicts for:
anaconda==2019.10 -> zeromq==4.3.1=h0a44026_3
spyder-unittest -> pyzmq -> zeromq[version='4.2.*|>=4.2.3,<4.3|>=4.2.5,<4.2.6.0a0|>=4.3.1,<4.4.0a0']
spyder -> pyzmq -> zeromq[version='4.2.*|>=4.2.3,<4.3|>=4.2.5,<4.2.6.0a0|>=4.3.1,<4.4.0a0']
pyzmq -> zeromq[version='4.2.*|>=4.2.3,<4.3|>=4.2.5,<4.2.6.0a0|>=4.3.1,<4.4.0a0']
spyder-kernels -> pyzmq[version='>=17'] -> zeromq[version='>=4.2.3,<4.3|>=4.2.5,<4.2.6.0a0|>=4.3.1,<4.4.0a0']
anaconda==2019.10 -> pyzmq==18.1.0=py36h0a44026_0 -> zeromq[version='>=4.3.1,<4.4.0a0']
jupyter_client -> pyzmq[version='>=13'] -> zeromq[version='4.2.*|>=4.2.3,<4.3|>=4.2.5,<4.2.6.0a0|>=4.3.1,<4.4.0a0']
notebook -> pyzmq[version='>=17'] -> zeromq[version='4.2.*|>=4.2.3,<4.3|>=4.2.5,<4.2.6.0a0|>=4.3.1,<4.4.0a0']

Package pyopenssl conflicts for:
prometheus_client -> twisted -> pyopenssl[version='>=16.0.0']
anaconda==2019.10 -> urllib3==1.24.2=py36_0 -> pyopenssl[version='>=0.14']
conda[version='>=4.8.2'] -> pyopenssl[version='>=16.2.0']
urllib3 -> pyopenssl[version='>=0.14']
requests -> urllib3[version='>=1.21.1,<1.26,!=1.25.0,!=1.25.1'] -> pyopenssl[version='>=0.14']
conda-build -> conda[version='>=4.5'] -> pyopenssl[version='>=16.2.0']
anaconda==2019.10 -> pyopenssl==19.0.0[build='py37_0|py36_0|py27_0']

Package tblib conflicts for:
dask -> distributed[version='>=2.10.0'] -> tblib
anaconda==2019.10 -> distributed==2.5.2=py_0 -> tblib
distributed -> tblib
anaconda==2019.10 -> tblib==1.4.0=py_0
```

**Comment by jitseniesen** [comment]
I am afraid that I don't know the ins and outs of how Anaconda works and in particular I don't understand the conflict output so in such instances I basically mess around until it works. I found it helps if you install the "miniconda" version and then add everything you are interested in.

I believe the `anaconda` package depends on the specific versions of all packages in the version of Anaconda that you are installing, which means that it becomes hard to install or upgrade packages. So I would try removing it with `conda remove anaconda`. If this removes packages that you want to have, then install them back afterwards.

@ccordoba12 Please correct me or add additional help if necessary.

**Comment by gabrielburcea** [comment]
@ccordoba12  solved the issue. See: https://stackoverflow.com/questions/60300787/unit-testing-tab-does-not-appear-in-spyder-in-mac/60338462#60338462

**Comment by jitseniesen** [comment]
Great!

**Comment by ccordoba12** [comment]
@gabrielburcea, great to know you were able to solve this problem!
