### ISSUE TITLE
Do first release

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#14]
Once plugin is in a decent state, put it on PyPI (and Conda?) and publicize
- [x] publish 0.1.beta on PyPI 
- [x] publish 0.1.beta on conda (the beta versions are mainly to test packaging)
- [ ] publish 0.1 on PyPI
- [ ] publish 0.1 on conda
- [ ] send announcement

**Comment by jitseniesen** [comment]
I feel the plugin is starting to get in shape after merging #39. My current plan is to release immediately after Spyder v3.1 is released.

**Comment by ccordoba12** [comment]
Before doing that, let me open a new PR to make this plugin compatible with Spyder 4 too.

I'll do it this weekend :-)

**Comment by jitseniesen** [comment]
Now that Spyder 3.1 is released, I will work on releasing this plugin.

**Comment by goanpeca** [comment]
@jitseniesen I can give you a walkthrough of the release process @jitseniesen for both pypi and conda.

**Comment by jitseniesen** [comment]
@goanpeca Thanks, yes, that would be good.

**Comment by goanpeca** [comment]
Do you want to setup a hangout?

**Comment by jitseniesen** [comment]
Not today. Do you have time tomorrow?

**Comment by goanpeca** [comment]
Sure, anytime tomorrow is good for me, as long as I am awake :-p

**Comment by jitseniesen** [comment]
How about tomorrow 15:00 GMT?

**Comment by goanpeca** [comment]
Sure

**Comment by jitseniesen** [comment]
Done!
