### ISSUE TITLE
Check whether test framework is installed

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#15]
so that we can give a good error message if it is not

**Comment by goanpeca** [comment]
@jitseniesen since the plan for 4.0 is to have a more language agnostic Spyder, do you think it is worth making this a generic unit test widget? plus the one with Python support?

**Comment by jitseniesen** [comment]
> @jitseniesen since the plan for 4.0 is to have a more language agnostic Spyder, do you think it is worth making this a generic unit test widget?

Yes, at least at first thought. We'll have to see how it works out.

**Comment by jitseniesen** [comment]
Need also to check for other dependencies, e.g. lxml

**Comment by goanpeca** [comment]
Is the check like a safeguard in case someone uninstalled something by accident? cause the plugin installation should define the dependencies, no?

**Comment by jitseniesen** [comment]
Good point. I haven't really thought about installation because I have never distributed Python modules. Regarding lxml, I guess it is indeed a safeguard. But there are also the test frameworks themselves (py.test, nose, unittest, ...). I don't want the user to have to install all the frameworks, so the plugin should check which ones are installed and prevent the user from running one that is not installed.

**Comment by goanpeca** [comment]
Hmmm true, I can help on the packaging side ;-).

unittest comes with python, and nose is an extension to unitests, so I dont think it is a bad idea to install pytest and nose by default. I think it makes sense
