### ISSUE TITLE
Make plugin depend on Python 3

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#154]
The plugin does not work in Python 2 anymore because the `nonlocal` keyword is used in `pytestrunner.py`. So I should make the plugin Python 3 only before releasing the next version.

_Originally noted in https://github.com/spyder-ide/spyder-unittest/pull/150#issuecomment-623683349_

**Comment by goanpeca** [comment]
@jitseniesen remember to add the check on the `check_compatibility` method of the plugin
