### ISSUE TITLE
Spyder internal error upon "Show output"

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder-unittest#158]
Occurs whether testing finished, interrupted in collection, or interrupted in testing. I'm using latest Spyer and spyder-unittest, Win-10 OS.

<img src="https://user-images.githubusercontent.com/16495490/82902811-17f0cf80-9f71-11ea-9053-eef3689a740c.png" width="400">

**Comment by jitseniesen** [comment]
The latest spyder-unittest is version 0.4.1. This version has a menu item "Dependencies", so your picture does not look like it comes from the latest spyder-unittest. 

I can't help you further without any details on the error.

**Comment by OverLordGoldDragon** [comment]
@jitseniesen My mistake - the latest works fine.
