### ISSUE TITLE
unit test in venvs

### ISSUE THREAD

**Issue by f-brinkmann** [spyder-ide/spyder-unittest#159]
## Description:

I have unit tests that fail due to an import error when I run the tests from within Spyder. However, when I run the test on the console, everything works fine, if I run it in the correct environment. Using the console and my root environment, I get the same import error as in Spyder. This makes me wonder if spyder-unittest uses the correct environment. In Spyder, I set the environments through `Preferences > Python interpreter` and the correct environment is displayed in the status bar at the bottom.

## What is the expected output? What do you see instead?
I expect unit tests to path in Spyder, but they fail.

## Setup
I have Spyder and spyder-unittest installed in my root environment and the spyder-kernels in the venv I am using. I found that as a recommendation somewhere in the Spyder docs.

## Key versions and other information:

* Spyder version: 4.1.5
* Version of spyder-unittest plugin: 0.4.1
* Installation method for Spyder and the unittest plugin: Anaconda
* Python version: 3.8.5
* Testing framework used: py.test
* Testing framework version: 6.0.1
* Operating system: Windows 10

**Comment by closega** [comment]
I am running into the same issue.

**Comment by hottwaj** [comment]
This is a critical issue for me too.  There is no way to configure which venv is used for unittests

**Comment by jitseniesen** [comment]
The underlying reason for this bug is issue #65: the plugin does not honour the Python interpreter set in the preferences. I am going to close this as a duplicate as that issue. I understand that this breaks tests run in a venv which makes it a higher priority than I realized.
