### ISSUE TITLE
Plugin does not work with Spyder 5

### ISSUE THREAD

**Issue by ski123786** [spyder-ide/spyder-unittest#163]
### What steps will reproduce the problem?

Even after installing the below packages through anaconda navigator I don't find "Run Unit Test" option under Spyder IDEs "Run" menu or any Unit Testing tab. Please provide the resolution steps. Thanks!

spyder  5.0.1    py38haa244fe_0    conda-forge

spyder-kernels  2.0.2    py38haa244fe_0    conda-forge

spyder-unittest   0.3.1   py_1    conda-forge

**Comment by cg-mayrhofer** [comment]
What's the status here?

**Comment by bkaatz** [comment]
Checking in on this.
I have the latest spyder-5.1.1 and looking for the spyder-unittest plugin that works with it.
Thanks for your time and attention to this.

**Comment by jitseniesen** [comment]
I started the work on converting the plugin to work with Spyder 5.2

**Comment by bkaatz** [comment]
Thank you for your hard work!
It is most appreciated!  Thanks again.
