### ISSUE TITLE
Remove support for nose

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#178]
Nose has seen no updates since 2015, numpy switched away in 2018, I don't remember an explicit mention of nose in connection with this plugin in a long time, so I propose that we remove support for nose in v0.6 of this plugin.

**Comment by juliangilbey** [comment]
There is nose2 as a potential alternative: https://docs.nose2.io/en/latest/

Dmitry Shachnev (a Debian Python maintainer) has just proposed a mass-bug filing against packages still using nose: https://lists.debian.org/debian-python/2022/08/msg00065.html

So I'd be OK with seeing nose support removed from this plugin, though if nose2 is a reasonable substitute and it is relatively easy to switch the code from nose support to nose2 support, that might be preferable to a wholesale removal.

Best wishes, Julian

**Comment by jitseniesen** [comment]
I saw that Dmitry went ahead and filed a bug against the Debian package. Since the nose dependency is optional (except for running the test suite), I guess you can just disable the tests that run nose in the Debian package if you want to get rid of the Build-Depends.

Regarding nose2, there has never been a demand for it and I don't use it myself so I am not super keen. However, it looks lie it may be really easy to change the code from nose to nose2. There are apparently thousands of repos on Github that use nose2 so it does see some use. I will try it and see how it goes. Thanks for the suggestion.

**Comment by jitseniesen** [comment]
It turns out it was quite easy to support nose2, so that is what I am going to do.
