### ISSUE TITLE
Release v0.5.1

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#183]
My plan is to release version 0.5.1 with the code as it is now between 29 August and 5 September. The main change is the work by @stevetracvc in PR #174 and #175.

**Comment by ccordoba12** [comment]
We plan to release Spyder 5.3.3 on August 29th, so perhaps you'd like to wait until then to check that that version doesn't break anything here.

**Comment by stevetracvc** [comment]
I can help take a look when the new Spyder gets released. Also, #182 looks awesome, that'll be in there too? I got stuck trying to figure out how to get the versions from the different interpreter.

**Comment by jitseniesen** [comment]
@stevetracvc , sorry, I saw your message only after I did the release so I did not take you up on your offer. The release does include #182.
