### ISSUE TITLE
spyder-unittest doesn't stop on breakpoints

### ISSUE THREAD

**Issue by yurivict** [spyder-ide/spyder-unittest#191]
## Description of your problem

There is only a "Run" button on the unit test pane.
When breakpoints are set and the Run button on the unittest pane or the 'Debug file' button on top of the screen is pressed - it doesn't stop on breakpoints.

## Key versions and other information:

* Spyder version: 5.4.0
* Version of spyder-unittest plugin: 0.5.1
* Installation method for Spyder and the unittest plugin: FreeBSD port
* Python version: 3.9
* Testing framework used: py.test
* Testing framework version: 7.2.0
* Operating system: FreeBSD 13.1

**Comment by jitseniesen** [comment]
Thanks for the suggestion. I agree, this would be very useful. It's also a long-standing issue, which has been discussed under #126. I am going to close this issue to keep the discussion centralized, but please understand that I'm not rejecting your suggestion; quite the contrary.
