### ISSUE TITLE
Test configuration

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder-unittest#199]
## Description of your problem
I'd like to run my tests with the flag `--mpl` to enable `pytest-mpl`, but as far as I can see it is not possible?

As a minor feature request (as in less "urgent"), it would be nice to be able to set environment variables when running the tests as well. For example `PYTEST_QT_API`. It is possible to set it before starting Spyder, but sometimes one would like to change without restarting or simply forget to set it...

## What steps will reproduce the problem?

1. 
2. 
3. 

### Paste traceback/error below (if applicable)
*(Copy from error dialog or `View > Panes > Internal Console`)*

```python-traceback

<!--- PASTE TRACEBACK HERE --->

```

## Key versions and other information:

* Spyder version: 5.4.2
* Version of spyder-unittest plugin: 0.5.1
* Installation method for Spyder and the unittest plugin: conda
* Python version: 3.10.10
* Testing framework used: py.test
* Testing framework version:
* Operating system:

**Comment by jitseniesen** [comment]
@oscargus You're right, that's not possible at the moment. I can add a text field to the test configuration window where you can specify additional command line arguments like `--mpl`. Would that work for you?

**Comment by oscargus** [comment]
That would be awesome! Thanks!
