### ISSUE TITLE
Update plugin for compability with Spyder 6.0.0alpha2

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#215]
Per PR spyder-ide/spyder#21101, specifically https://github.com/spyder-ide/spyder/pull/21101#issuecomment-1629480210, `SpyderPluginV2.get_description` must be a static method now and `SpyderPluginV2.get_icon` a class or static method.

**Comment by mrclary** [comment]
FYI, this must be completed before including in conda-based installers.
