### ISSUE TITLE
Command-line arguments are not saved

### ISSUE THREAD

**Issue by abdullahkhalids** [spyder-ide/spyder-unittest#216]
## Description of your problem

Following #199 it is possible to add command-line arguments via the config window.

However,  these arguments are not saved, and have to be re-entered on every restart.

## What steps will reproduce the problem?

1. Add command-line arguments such as `--doctest-modules` via the config window.
2. Run tests to confirm that arguments are being used.
3. Restart Spyder.
4. Command-line arguments field is empty.

## What is the expected output? What do you see instead?
Command-line arguments should remain saved after restart. Ideally, these should saved per-spyder-project but even a global save would be a good starting point.

## Key versions and other information:

* Spyder version: 5.4.3
* Version of spyder-unittest plugin: 0.6.0
* Installation method for Spyder and the unittest plugin: Conda
* Python version: 3.10.12
* Testing framework used: pytest
* Testing framework version: 7.4.0
* Operating system: Linux/Debian

**Comment by jitseniesen** [comment]
Hi, thanks for the suggestion. This makes sense to me so I'm planning to include it in the next release.

**Comment by jitseniesen** [comment]
@abdullahkhalids Do you want fix this yourself and open a pull request?

**Comment by abdullahkhalids** [comment]
I took a look. It seems it is possible for me to do this. I will try and get back to you in a weekend or two.

**Comment by jitseniesen** [comment]
> I took a look. It seems it is possible for me to do this. I will try and get back to you in a weekend or two.

That would be great. Don't hesitate to ask any questions that you may have.
