### ISSUE TITLE
conda-forge is a valid install?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder-unittest#220]
I used `conda install -c conda-forge spyder-unittest`, works with latest `spyder 5.5.2`. The one on `conda-forge` is also more up to date (0.6.0 vs 0.5.1 on [spyder-ide](https://anaconda.org/spyder-ide/spyder-unittest)). [Installation](https://github.com/spyder-ide/spyder-unittest?tab=readme-ov-file#installation) points to `spyder-ide`.

Is `conda-forge` fine? It seems preferable with [miniforge](https://github.com/conda-forge/miniforge).

**Comment by jitseniesen** [comment]
You are right, people should use `conda-forge`. The installation document is outdated and I should change it. Thanks for alerting me.
