### ISSUE TITLE
Create a conda package

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-unittest#23]

**Comment by goanpeca** [comment]
Initial, skeleton is complete, but once this is released, this package should be created on conda-forge.

**Comment by jitseniesen** [comment]
See PR at conda-forge/staged-recipes#2258

**Comment by ccordoba12** [comment]
We need to move these packages to the `spyder-ide` channel afterwards to avoid pesky conflicts between the default Anaconda channels and conda-forge.

Just a reminder to do that :-)

**Comment by goanpeca** [comment]
>We need to move these packages to the spyder-ide channel afterwards to avoid pesky conflicts between the default Anaconda channels and conda-forge.

Now that you mentioned that I updated all recipes and dependencies for ciocheck and copied them to spyder-ide. We can start using Py36 on CI. I already migrated all tests on Navigator so its working ok.

**Comment by ccordoba12** [comment]
> We can start using Py36 on CI

Feel free to do it. I don't have time to that for the next two weeks :-/

**Comment by goanpeca** [comment]
I will today, just take a look at it when I am done :-)

**Comment by ccordoba12** [comment]
Sure, I'll take a look at it :-)

**Comment by jitseniesen** [comment]
> We need to move these packages to the `spyder-ide` channel afterwards to avoid pesky conflicts between the default Anaconda channels and conda-forge.

Now that the spyder-uniittest package is on conda-forge [here](https://anaconda.org/conda-forge/spyder-unittest), how do I get it to spyder-ide?

**Comment by goanpeca** [comment]
`$ anaconda copy conda-forge/spyder-unitest/0.1b2 --to-owner spyder-ide`

**Comment by jitseniesen** [comment]
Using my Anaconda account (`jitseniesen`), I get:
```
[BinstarError] ("you do not have access to create a package on spyder-ide's account", 400)
```

**Comment by goanpeca** [comment]
Oops, let me give you access!

**Comment by jitseniesen** [comment]
Thanks.

Now available on both conda-forge and spyder-ide channels, so closing ...
