### ISSUE TITLE
Rename repo to spyder-unittest

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-unittest#24]
Also rename main module `spyder_unittesting` to `spyder_unitest`?

**Comment by ccordoba12** [comment]
+1 from me :-)

**Comment by jitseniesen** [comment]
Fine with me. I suppose it's intentional to call the repo `spyder-unittest` (with a hyphen) and the module `spyder_unittest` (with an underscore).

**Comment by goanpeca** [comment]
Yep, its the usual way :-p

**Comment by jitseniesen** [comment]
Done.
