### ISSUE TITLE
Make code translation friendly?

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-unittest#30]
Use `_()` whenever gui text is exposed

Find translators for the project? (We could ask the same translators of spyder)

**Comment by StefRe** [comment]
I think this one can be closed. I checked the source code and found that every string exposed to the GUI is enclosed in `_()`.  

But I have a question: if I introduce new strings to the GUI (as e.g. in #146 [here](https://github.com/spyder-ide/spyder-unittest/blob/f88518b6f59aa0765491008571ed5e140f86d123/spyder_unittest/widgets/unittestgui.py#L179)), do I have to manually add them to `spyder_unittest.pot` or will this be done automatically at certain intervals?

**Comment by jitseniesen** [comment]
I don't know, I think there is a tool that does that. @goanpeca ?

**Comment by goanpeca** [comment]
Yes, we use this https://github.com/spyder-ide/gettext-helpers

We install from git source directly and then run what is explained on the README.

We usually run this before a release, so that https://crowdin.com/project/spyder-unittest can be updated.

(I will be adding some sort of bot to make these tasks easier via github actions)

**Comment by jitseniesen** [comment]
Fixed by PRs #168, #169 and #170.
