### ISSUE TITLE
Extend plugin to compute and display coverage

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#33]
This is still some way off.

**Comment by stevetracvc** [comment]
So I started looking at this and to just get the coverage in the "show output" area it's fairly simple (at least for pytest). What did you have in mind?

I'm fairly new to this arena, but I changed the pytestrunner func to this:

```
    def create_argument_list(self):
        """Create argument list for testing process."""
        pyfile = os.path.join(os.path.dirname(__file__), 'pytestworker.py')
        return [pyfile, str(self.reader.port),
                f"--cov={os.getcwd()}", "--cov-report=term-missing"]
```
and that seems to give me what I need.

**Comment by ccordoba12** [comment]
@stevetracvc, please go ahead and submit a PR with your patch so we can take a look at it.

**Comment by stevetracvc** [comment]
@ccordoba12 I added a bit more, allowing the end user to toggle coverage on and off. I don't have anything using nose, so I didn't test that part, but I checked real quickly in their manual for what additional command line args it needs. If you could test that I'd appreciate it :) Also, I don't know how to do it with unittest itself, so I just disable the checkbox if you choose unittest

**Comment by ccordoba12** [comment]
> If you could test that I'd appreciate it :)

Could you remove Nose support in a separate PR instead? Nose was deprecated years ago, so I think we shouldn't depend on it here anymore.

**Comment by stevetracvc** [comment]
Sure thing! I'll look at those errors too, weird I don't think the tests failed on my machine, but I'm guessing it's because I ran it from the plugin in a project :)
