### ISSUE TITLE
Avoid qtbot.wait in test

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#35]
See `spyder_unittest/widgets/tests/test_unittestgui.py`.

----

This refers to the `qtbot.wait` in that file

**Comment by jitseniesen** [comment]
Windows hangs (maybe disabling xdist on windows...) and OSX fails the test.

**Comment by goanpeca** [comment]
Yep, will disable xdist for win and try again.

For osx it might be that it needs more time so we can check that one ;-)

**Comment by goanpeca** [comment]
@jitseniesen I started the enforcement of pydostyle and pep8 and flake8 and isort, 

Could you complete these docstrinngs?
```
  pydocstyle
  ----------
    162:     D102: Missing docstring in public method
    177:     D102: Missing docstring in public method
    182:     D102: Missing docstring in public method
    187:     D102: Missing docstring in public method
    255:     D102: Missing docstring in public method
    259:     D102: Missing docstring in public method
    276:     D102: Missing docstring in public method
    284:     D102: Missing docstring in public method
    290:     D102: Missing docstring in public method
    397:     D102: Missing docstring in public method
```

**Comment by goanpeca** [comment]
For the widget we need to define a couple of signals, but the most important one is that emits that it finished.

To make this plugin more generic, we should try something like this
https://github.com/ContinuumIO/ciocheck/blob/master/ciocheck/linters.py#L110

if based on parsing the output, but we could also have a json parser, cause right now this plugin is too python oriented.

**Comment by goanpeca** [comment]
@jitseniesen on windows I am getting a message box saying "process failed to start" and that is why it is hanging, now why are we getting that ?

https://github.com/spyder-ide/spyder-unittest/blob/master/spyder_unittest/widgets/unittestgui.py#L261
