### ISSUE TITLE
Save selected test framework

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#43]
The test framework (nose, py.test, unittest) should be saved between invocations of Spyder so that the user does not have to specify the test framework again after quitting Spyder. This should probably be done per project.

I guess this requires changes to Spyder ...

**Comment by ccordoba12** [comment]
Yep, my plan for Spyder 3.2 is to activate and improve options for projects (the code is already there, we just need to make it work).

**Comment by jitseniesen** [comment]
@ccordoba12 What is the status? Can plugins at the moment load and save options for projects? If yes, how? If no, is there a plan and/or should I implement it myself? I couldn't find an issue about this.

**Comment by ccordoba12** [comment]
Sorry, there's no progress yet for this. We're going to have a sprint next week, so we plan to address, or at least define a plan on how we should solve it.

**Comment by jitseniesen** [comment]
No problem, it's not really urgent, but it would be good to have a plan.
