### ISSUE TITLE
KeyError: 'system-err'

### ISSUE THREAD

**Issue by bilderbuchi** [spyder-ide/spyder-unittest#46]
When I run pytest unit tests using this plugin on an internal package of mine, I get in the internal console
```
Traceback (most recent call last):
  File "c:\users\bilderbuchi\desktop\coding\spyder-unittest\spyder_unittest\backend\testrunner.py", line 162, in finished
    testresults = self.load_data()
  File "c:\users\bilderbuchi\desktop\coding\spyder-unittest\spyder_unittest\backend\testrunner.py", line 206, in load_data
    category = STATUS_TO_CATEGORY[status]
KeyError: 'system-err'
```
The code/tests is not public, so I can't offer a good repro, but from the key I guess something in the tests goes wrong, and that status is not coded in yet? Vanilla pytest on the package works correctly, as do vanilla pytest tests and Spyder-run tests on spyder-unittest.

**Comment by bilderbuchi** [comment]
Btw, the class name `TestRunner` gets collected by pytest, and I couldn't find a way to ignore/flag that away, as it gets imported in spyder-unittest/backend/tests/test_testrunner.py

**Comment by jitseniesen** [comment]
The KeyError is triggered when you have a passing test that prints something to stdout or stderr. I need to fix this ASAP.

By the way, thanks for all your comments.

**Comment by bilderbuchi** [comment]
Thanks!
