### ISSUE TITLE
pytest statuses "expected-fail" and "unexpectedly passing" not yet reflected in Category

### ISSUE THREAD

**Issue by bilderbuchi** [spyder-ide/spyder-unittest#47]
Hi!

Just to note this (can't currently work on this), the pytest statuses "expected to fail" (XFAIL, shown as an "x" in test results) and "“unexpectedly passing” (XPASS) are not yet available in [https://github.com/spyder-ide/spyder-unittest/blob/52af625e6a526c218d3a7930fdd348ab5716c724/spyder_unittest/backend/testrunner.py#L28](Category), and probably should be at some point.
See also http://doc.pytest.org/en/latest/skipping.html?highlight=expected%20fail#skip-and-xfail-dealing-with-tests-that-cannot-succeed

**Comment by jitseniesen** [comment]
In the meantime, `Category.SKIP` has been used to not only contain skipped tests but also xpass and xfail tests. So I guess it is enough to rename `Category.SKIP` to `Category.MISC`.

**Comment by bilderbuchi** [comment]
Can't check because on the phone, but if Category is a flagint enum, it should hopefully be possible to cover both the more specific categories of pytest and frameworks that only offer pass/fail/skip with one logic.

**Comment by bilderbuchi** [comment]
...if that's the reason you want to go for category.misc, that is.

**Comment by jitseniesen** [comment]
I think I may have misunderstood you. Why do you want `Category` to reflect xpass and xfail?

The Category is not directly user visible, but it does determine the background colour (currently, green for Category.OK = passing tests, red for Category.FAIL = failing tests, blank for Category.PENDING = pending tests and grey for Category.SKIP = the rest). Do you think that xfail, xpass and skip should all have different colours?

**Comment by bilderbuchi** [comment]
Ok, then I misunderstood. If it's primarily about the color scheme, I think xfail and xpass should be green, as they represent the test outcome matches the user's expectations, i.e. the test failed or passed, respectively. I wonder if pytest can colour output, that could also offer indications.

**Comment by jitseniesen** [comment]
I understand your reasoning but I'm wondering whether this may actually be more confusing. For the record, if you run py.test with the `--verbose` switch, then "passed" is coloured green, "failed" is coloured red, and "skipped", "xfail" and "xpass" are all coloured yellow.

I'm going to leave this issue open for the moment.

**Comment by StefRe** [comment]
@bilderbuchi :
> I think xfail and xpass, should be green as they represent the test outcome matches the user's expectations, i.e. the test failed or passed, respectively. 

I'm afraid there is some misunderstanding here: `xpass` means a test that was **expected to fail** passed **UN**expectedly - so it didn't meet the user's expectation and hence should be red and not green.

**Comment by bilderbuchi** [comment]
Ah, sounds reasonable, thanks!
