### ISSUE TITLE
Use py.test's API to run tests

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#50]
At the moment, we parse the JUnitXml output, which has the advantage that we can use the same code for py.test and nose. However, the JUnitXml output does not have all the information we need. In particular, this issue is a prerequisite for #12, #13 and #47.

**Comment by goanpeca** [comment]
look at pytest-json that might be useful

**Comment by jitseniesen** [comment]
I now think a better idea is to run the tests individually using py.test's API. This should give us the results in a convenient form, so we do not have to parse the output.
