### ISSUE TITLE
Add the test suite to the release tarball

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/spyder-unittest#56]
Please consider adding the tests to the release tarball uploaded on PyPI. PyPI is the primary source for packaging on Linux distributions and having the test suite would be highly beneficial for QA / CI purposes.

Thanks,
Ghis

**Comment by ccordoba12** [comment]
@jitseniesen, in case you don't know him, @ghisvail is the current Spyder packager in Debian. So he seems to be considering to add this plugin to that distro (and so to Ubuntu too ;-)

**Comment by ghisvail** [comment]
Indeed, see [Bug-Debian#854363](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854363)

**Comment by ccordoba12** [comment]
Great!! Thanks @ghisvail!

**Comment by ghisvail** [comment]
@ccordoba12 Let me know whether there are other plugins that would be desirable to ship alongside the packaged `spyder` in the future. I usually monitor ANNs in the digest sent from the forum, but I could miss some of those.

**Comment by ccordoba12** [comment]
Will do. We're are working on four plugins right: vim (to have vim kebindings in the Editor), notebook (to embed the Jupyter notebook in Spyder), terminal (to have OS terminals) and reports (to create reports in markdown using Pweave).

None of them are functional but they will be in a couple of months.

**Comment by ghisvail** [comment]
I see. Please make sure they use a consistent naming scheme (some have `spyder.<plugin>`, others have `spyder-<pluging>`). Otherwise, I could normalize the source package names in Debian (for instance `spyder-plugin-<plugin>`), but I would prefer if such normalization was agreed upstream instead.

I am looking forward to the vim plugin :-)

**Comment by ccordoba12** [comment]
> Please make sure they use a consistent naming scheme

Ok, thanks for noticing it.

**Comment by jitseniesen** [comment]
@ghisvail I have been using Debian myself for longer than I remember, so thanks for all the work you're doing on it.

I'm happy to add the tests to the tar ball. I hadn't really thought about it. My plan is to wait a week or so to see whether any major bugs turn up and then include the tests in a 0.1.1 release.

**Comment by ghisvail** [comment]
I have submitted the package for review. It is working fine with the packaged version of `spyder` coming in Debian Stretch. Because of #57, I have put a hard dependency on having both `nose` and `pytest` installed when installing `spyder-unittest`. Depending on how the issue gets solved, this relationship could be relaxed later.

**Comment by jitseniesen** [comment]
@ghisvail Is there any standard which we should follow which makes it easier for you to find and run the tests automatically?

**Comment by ghisvail** [comment]
You mean regarding the Debian packaging of `spyder-unittest`?

**Comment by jitseniesen** [comment]
I mean, anything which makes it easier for you to package spyder-unitttest for Debian in such a way that the tests are run.

**Comment by ghisvail** [comment]
Actually yes, it would be great if you could test whether the tests can be run with `pytest-xvfb` instead of setting-up `xvfb` manually.

It would simplify things a great deal if testing of future `spyder` plugins could be normalized to using `pytest-qt` + `pytest-xvfb`, assuming this is verified to work with `spyder-unittest`.

**Comment by jitseniesen** [comment]
@ghisvall The tests work with `pytest-xvfb`, at least locally on my machine. There is a harmless py.test warning about the `TestRunner` class.

Version 0.1.1, packaged with the tests, is now on PyPI. I don't want to make an announcement (the changes are too small), so I'm telling you this way.
