### ISSUE TITLE
Depend on nose and pytest at installation

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/spyder-unittest#57]
Right now, the plugin offers to run `pytest` or `nose` on a folder or your choice. There is however nothing forcing users to have any, one or both test frameworks available in their environment. Regardless, the selection box offer all test frameworks, which may lead to problems later.

Could this be made a bit more adaptive somehow? For instance, by greying out selection of test frameworks for which a test import failed?

Otherwise, perhaps there should be an install dependency on `nose` *and* `pytest`?

**Comment by jitseniesen** [comment]
> Could this be made a bit more adaptive somehow? For instance, by greying out selection of test frameworks for which a test import failed?

This is indeed the plan. Actually, this is what issue #15 is about. But it needs to be programmed.

> Otherwise, perhaps there should be an install dependency on nose and pytest?

Yep, these dependencies should be added while the greying out is not yet implemented.

**Comment by ghisvail** [comment]
> Yep, these dependencies should be added while the greying out is not yet implemented.

Thanks for confirming. That's what I have done.

**Comment by bilderbuchi** [comment]
> Yep, these dependencies should be added while the greying out is not yet implemented.

You can check if packages are available with `importlib.util.find_spec()`: 
```
nose_available = bool(importlib.util.find_spec('nose'))
pytest_available = bool(importlib.util.find_spec('pytest'))
```
This is Python 3.4+, and has the benefit that it does not import the package in question, as opposed to the older try-import-except-ImportError method.  
See http://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it and https://docs.python.org/3/library/importlib.html#importlib.util.find_spec
