### ISSUE TITLE
Normalized copyright information

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/spyder-unittest#58]
`setup.py` lists "The Spyder Project Contributors"

`LICENSE.txt` lists "Joseph Martinot-Lagarde"

The copyright headers in the source files list "Spyder Project Developers"

Please normalize this. Right now, the copyright / authorship information is confusing.

Also, please consider adding dates to the copyright headers.

**Comment by jitseniesen** [comment]
> Please normalize this. Right now, the copyright / authorship information is confusing.

Thanks; will do.

> Also, please consider adding dates to the copyright headers.

What is the advantage about this? I am worried about having to continuously update the dates.

**Comment by ghisvail** [comment]
> I am worried about having to continuously update the dates.

A well-formed copyright notice is composed of:
- The symbol (c) or word "Copyright"
- The year of **first** publication
- The name of the copyright owner
