### ISSUE TITLE
Allow a user to run a specific unit test

### ISSUE THREAD

**Issue by PGijsbers** [spyder-ide/spyder-unittest#88]
Is it possible for a user to run a specific unit test, rather than all tests in the directory?
If not, I think it would be a useful addition since I don't want to rerun all unit tests to see if I fixed the specific one I am debugging (I currently use nose).

**Comment by jitseniesen** [comment]
No, this is not possible, but it is a good idea. 

I wonder if you could help me with realizing this. Any ideas on the user interface; that is, how will the user choose which test to run? Additionally, do you know how to tell nose that you want to run only one test? I don't use nose myself.

**Comment by PG-TUe** [comment]
> Any ideas on the user interface; that is, how will the user choose which test to run?

I get a list of unit test results after running all tests. To me it makes sense to be able to right-click for a context menu, which allows me to 'rerun test'.
Alternatively, you could show all discovered tests before running them, so I do not need to run them to get an overview of all tests. From there, similarly I could run a specific test through the context menu.

> Additionally, do you know how to tell nose that you want to run only one test? I don't use nose myself.

[This](https://coderwall.com/p/mq7t1g/running-a-specific-test-in-python-with-nose) gives an example, given the tests are setup as a module. I just started working on a project where this is not the case, so I am still trying to figure out what the correct structure is there. I'll update when I find out.

**Comment by goanpeca** [comment]
@PG-TUe this would be a great addition, interested in working on it?

**Comment by PG-TUe** [comment]
Perhaps later, but probably not before the end of this year :( I just can't find the time. Especially since I've done nothing of the sort before, it might take some extra time to get acquainted with the workings.

**Comment by jitseniesen** [comment]
Running tests separately via right-click is a great idea.

@PG-TUe Any help is welcome. I definitely won't have time to work on it before Christmas; there are other things I want to do first. I'm more than happy  to give you some pointers to get you started. It's a good way to learn this kind of thing.

**Comment by PG-TUe** [comment]
Alright, if I find the time, I'll be sure to report back 👍

**Comment by ccordoba12** [comment]
I need this to run the Spyder test suite too.
