### ISSUE TITLE
Enable sorting in table of test results

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#94]
It would be especially useful to be able to sort so that test failures are at the top

**Comment by bilderbuchi** [comment]
Please make that optional, though. Imo this plugin should mirror the behaviour/output of the test frameworks as much as feasible.

**Comment by jitseniesen** [comment]
At the moment, I envisage that results are displayed in the order that they are reported, and that the user will have to click on the header row in order to sort.

**Comment by bilderbuchi** [comment]
Sounds good!
